# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/schemas/v3.0/schema.yaml
openapi: 3.0.0
info:
  title: Oinkos
  version: 1.0.5
paths:
  /user:
    get:
      description: Get the current user's information
      operationId: get_user
      security:
        - BearerAuth: []

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    default: false
                  username:
                    type: string
                  id:
                    type: string
                  email:
                    type: string
                  balance:
                    type: number
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: boolean
                    default: true
                  reason:
                    type: string
                    enum:
                      - "JWTKitError(errorType: signatureVerificationFailed)"
                      - Unauthorized

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

    BearerAuth:
      type: http
      scheme: bearer
